name = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print(f'Seu nome em maiúscula é {name.upper()}')
print(f'Seu nome em minúscula é {name.lower()}')
print(f'Seu nome tem ao todo {len(name) - name.count(' ')} letras')
separa = name.split()
print(f'Seu primeiro nome é {separa[0]} e ele tem {len(separa[0])} letras')